pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t yt-seo-insights-generator .'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Running tests..."'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying..."'
            }
        }
    }
}